package main;

public class adoptMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adoptMenu.class.getName());

    public adoptMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        ContactField = new javax.swing.JTextField();
        adoptNowBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCats = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setText("Adopter's Information");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 40, -1, -1));

        NameField.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 300, -1));

        ContactField.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        getContentPane().add(ContactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 300, -1));

        adoptNowBtn.setText("Adopt the cat :)");
        adoptNowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptNowBtnActionPerformed(evt);
            }
        });
        getContentPane().add(adoptNowBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jLabel1.setText("Adoption process will take a few days. Verification process will be done through email and or interviews on video call");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 260, -1, -1));

        listCats.setBorder(javax.swing.BorderFactory.createTitledBorder("Select a Cat to adopt"));
        listCats.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCats);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adoptNowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptNowBtnActionPerformed

    }//GEN-LAST:event_adoptNowBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContactField;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton adoptNowBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listCats;
    // End of variables declaration//GEN-END:variables
}
