package main;

import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;

public class adoptMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adoptMenu.class.getName());
    private static final java.util.regex.Pattern EMAIL_PATTERN = java.util.regex.Pattern.compile("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$");
    private static final java.util.regex.Pattern PHONE_PATTERN = java.util.regex.Pattern.compile("^\\d{11}$");

    public adoptMenu() {
        initComponents();
        loadAvailableCatsForAdoption();
    }

    private static final class CatItem {

        final int id;
        final String name;

        CatItem(int id, String name) {
            this.id = id;
            this.name = (name == null) ? "" : name;
        }

        @Override
        public String toString() {
            return name;
        }
    }

    private void loadAvailableCatsForAdoption() {
        SwingUtilities.invokeLater(() -> {
            DefaultListModel<CatItem> model = new DefaultListModel<>();

            String sql
                    = "SELECT c.cat_id, c.name "
                    + "FROM cat c "
                    + "LEFT JOIN ( "
                    + "  SELECT a1.cat_id, a1.status FROM adoption_status a1 "
                    + "  JOIN (SELECT cat_id, MAX(changed_at) AS maxc FROM adoption_status GROUP BY cat_id) a2 "
                    + "    ON a1.cat_id = a2.cat_id AND a1.changed_at = a2.maxc "
                    + ") latest ON c.cat_id = latest.cat_id "
                    + "WHERE latest.status = 'Available' OR latest.status IS NULL "
                    + "ORDER BY c.name";

            try (Connection conn = main.stuff.dbconn.getConnection(); PreparedStatement ps = conn.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {

                while (rs.next()) {
                    model.addElement(new CatItem(rs.getInt("cat_id"), rs.getString("name")));
                }

            } catch (SQLException ex) {
                logger.log(Level.WARNING, "Failed to load available cats for adoption", ex);
                model.clear();
                model.addElement(new CatItem(0, "<Error loading cats>"));
            }

            @SuppressWarnings("unchecked")
            JList<CatItem> lst = (JList<CatItem>) (Object) listCats;
            lst.setModel(model);
            lst.clearSelection();
        });
    }

    private static boolean isValidEmail(String email) {
        if (email == null) {
            return false;
        }
        return EMAIL_PATTERN.matcher(email).matches();
    }

    private static boolean isValidPhone(String phone) {
        if (phone == null) {
            return false;
        }
        String digits = phone.replaceAll("\\D", "");
        return PHONE_PATTERN.matcher(digits).matches();
    }

    private static boolean isValidContact(String contact) {
        return isValidEmail(contact) || isValidPhone(contact);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        ContactField = new javax.swing.JTextField();
        adoptNowBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCats = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(637, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setText("Adopter's Information");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 40, -1, -1));

        NameField.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 300, -1));

        ContactField.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        getContentPane().add(ContactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 300, -1));

        adoptNowBtn.setText("Adopt the cat :)");
        adoptNowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptNowBtnActionPerformed(evt);
            }
        });
        getContentPane().add(adoptNowBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jLabel1.setText("Adoption process will take a few days. Emails and or interviews will happen before adoption is finalized and processed.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        listCats.setBorder(javax.swing.BorderFactory.createTitledBorder("Select a Cat to adopt"));
        listCats.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCats);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, 180));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adoptNowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptNowBtnActionPerformed
        @SuppressWarnings("unchecked")
        JList<CatItem> lst = (JList<CatItem>) (Object) listCats;
        CatItem sel = (lst.getSelectedValue() instanceof CatItem) ? lst.getSelectedValue() : null;
        if (sel == null || sel.id == 0) {
            JOptionPane.showMessageDialog(this, "Please select a cat to adopt from the list.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String adopterName = NameField.getText() == null ? "" : NameField.getText().trim();
        String adopterContact = ContactField.getText() == null ? "" : ContactField.getText().trim();

        if (adopterName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your name.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (adopterContact.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your contact (email or phone).", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!isValidContact(adopterContact)) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a valid contact: either a valid email address or an 11-digit phone number.",
                    "Validation",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String contactToStore = adopterContact;
        if (isValidPhone(adopterContact)) {
            contactToStore = adopterContact.replaceAll("\\D", "");
        }

        String insertAdopterSql = "INSERT INTO adopter (name, contact_info) VALUES (?, ?)";
        String insertStatusSql = "INSERT INTO adoption_status (cat_id, status, changed_at, notes, adopter_id) VALUES (?, ?, NOW(), ?, ?)";

        try (Connection conn = main.stuff.dbconn.getConnection()) {
            try {
                conn.setAutoCommit(false);
                int newAdopterId = -1;
                try (PreparedStatement ps = conn.prepareStatement(insertAdopterSql, Statement.RETURN_GENERATED_KEYS)) {
                    ps.setString(1, adopterName);
                    ps.setString(2, contactToStore.isEmpty() ? null : contactToStore);
                    int affected = ps.executeUpdate();
                    if (affected == 0) {
                        throw new SQLException("Failed to insert adopter");
                    }
                    try (ResultSet keys = ps.getGeneratedKeys()) {
                        if (keys.next()) {
                            newAdopterId = keys.getInt(1);
                        }
                    }
                }

                try (PreparedStatement ps2 = conn.prepareStatement(insertStatusSql)) {
                    ps2.setInt(1, sel.id);
                    ps2.setString(2, "Other");
                    ps2.setString(3, "Adoption request submitted");
                    if (newAdopterId > 0) {
                        ps2.setInt(4, newAdopterId);
                    } else {
                        ps2.setNull(4, Types.INTEGER);
                    }
                    ps2.executeUpdate();
                }

                conn.commit();
            } catch (SQLException ex) {
                try {
                    conn.rollback();
                } catch (Throwable ignored) {
                }
                throw ex;
            } finally {
                try {
                    conn.setAutoCommit(true);
                } catch (Throwable ignored) {
                }
            }
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, "Failed to register adopter/request", ex);
            JOptionPane.showMessageDialog(this, "Failed to submit adoption request: " + ex.getMessage(), "DB error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, "Adoption request submitted. We will contact you regarding next steps.", "Request submitted", JOptionPane.INFORMATION_MESSAGE);
        NameField.setText("");
        ContactField.setText("");
        loadAvailableCatsForAdoption();
    }//GEN-LAST:event_adoptNowBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContactField;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton adoptNowBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listCats;
    // End of variables declaration//GEN-END:variables
}
