package main;

import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import javax.swing.ListSelectionModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class deleteCatsmenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(deleteCatsmenu.class.getName());

    public deleteCatsmenu() {
        initComponents();
        listCats.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        loadCats();
    }

    private void loadCats() {
        SwingUtilities.invokeLater(() -> {
            DefaultListModel<CatItem> model = new DefaultListModel<>();

            String sql = "SELECT cat_id, name FROM cat ORDER BY name";
            try (Connection conn = main.stuff.dbconn.getConnection(); PreparedStatement ps = conn.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
                boolean any = false;
                while (rs.next()) {
                    any = true;
                    model.addElement(new CatItem(rs.getInt("cat_id"), rs.getString("name")));
                }
                if (!any) {
                    model.addElement(new CatItem(0, "<No cats found>"));
                }
            } catch (SQLException ex) {
                logger.log(java.util.logging.Level.WARNING, "Failed to load cats", ex);
                model.clear();
                model.addElement(new CatItem(0, "<Error loading cats>"));
            }

            setListModel(model);
        });
    }

    private void setListModel(DefaultListModel<CatItem> model) {
        SwingUtilities.invokeLater(() -> {
            @SuppressWarnings("unchecked")
            javax.swing.JList<CatItem> lst = (javax.swing.JList<CatItem>) (Object) listCats;
            lst.setModel(model);
            lst.clearSelection();
        });
    }

    private static final class CatItem {

        final int id;
        final String name;

        CatItem(int id, String name) {
            this.id = id;
            this.name = name == null ? "" : name;
        }

        @Override
        public String toString() {
            return name;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listCats = new javax.swing.JList<>();
        DeleteCats = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete Cats");
        setMinimumSize(new java.awt.Dimension(422, 350));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listCats.setBorder(javax.swing.BorderFactory.createTitledBorder("List of Cats"));
        listCats.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCats);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 20, 280, 240));

        DeleteCats.setText("Delete");
        DeleteCats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCatsActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteCats, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteCatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCatsActionPerformed
        @SuppressWarnings("unchecked")
        javax.swing.JList<CatItem> lst = (javax.swing.JList<CatItem>) (Object) listCats;
        List<CatItem> selected = lst.getSelectedValuesList();

        if (selected == null || selected.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select one or more cats to delete.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        List<Integer> catIds = new ArrayList<>();
        StringBuilder names = new StringBuilder();
        for (CatItem ci : selected) {
            if (ci != null && ci.id > 0) {
                catIds.add(ci.id);
                if (names.length() > 0) {
                    names.append(", ");
                }
                names.append(ci.name);
            }
        }

        if (catIds.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No valid cat selected.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Delete selected cat(s): " + names.toString() + "? This will remove all related records and cannot be undone.",
                "Confirm delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        int totalDeletedCats = 0;
        int totalDeletedRelated = 0;

        try (Connection conn = main.stuff.dbconn.getConnection()) {
            try {
                conn.setAutoCommit(false);
                String deleteAdoptionSql = "DELETE FROM adoption_status WHERE cat_id = ?";
                String deleteBehaviorSql = "DELETE FROM behavior WHERE cat_id = ?";
                String deleteHealthSql = "DELETE FROM health_record WHERE cat_id = ?";
                String deleteIncidentSql = "DELETE FROM incident_report WHERE cat_id = ?";
                String deleteAssocSql = "DELETE FROM cat_caretaker WHERE cat_id = ?";
                String deleteCatSql = "DELETE FROM cat WHERE cat_id = ?";

                try (PreparedStatement psDelAdoption = conn.prepareStatement(deleteAdoptionSql); PreparedStatement psDelBehavior = conn.prepareStatement(deleteBehaviorSql); PreparedStatement psDelHealth = conn.prepareStatement(deleteHealthSql); PreparedStatement psDelIncident = conn.prepareStatement(deleteIncidentSql); PreparedStatement psDelAssoc = conn.prepareStatement(deleteAssocSql); PreparedStatement psDelCat = conn.prepareStatement(deleteCatSql)) {

                    for (Integer cid : catIds) {
                        int deletedRelatedForThisCat = 0;

                        psDelAdoption.setInt(1, cid);
                        deletedRelatedForThisCat += psDelAdoption.executeUpdate();

                        psDelBehavior.setInt(1, cid);
                        deletedRelatedForThisCat += psDelBehavior.executeUpdate();

                        psDelHealth.setInt(1, cid);
                        deletedRelatedForThisCat += psDelHealth.executeUpdate();

                        psDelIncident.setInt(1, cid);
                        deletedRelatedForThisCat += psDelIncident.executeUpdate();

                        psDelAssoc.setInt(1, cid);
                        deletedRelatedForThisCat += psDelAssoc.executeUpdate();

                        psDelCat.setInt(1, cid);
                        int catDeleted = psDelCat.executeUpdate();
                        if (catDeleted > 0) {
                            totalDeletedCats += catDeleted;
                            totalDeletedRelated += deletedRelatedForThisCat;
                        } else {
                            throw new SQLException("Failed to delete cat id=" + cid + " (it may not exist).");
                        }
                    }
                }

                conn.commit();
            } catch (SQLException ex) {
                try {
                    conn.rollback();
                } catch (Throwable ignored) {
                }
                throw ex;
            } finally {
                try {
                    conn.setAutoCommit(true);
                } catch (Throwable ignored) {
                }
            }
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Failed to delete cats", ex);
            JOptionPane.showMessageDialog(this, "Failed to delete selected cats: " + ex.getMessage(), "DB error", JOptionPane.ERROR_MESSAGE);
            loadCats();
            return;
        }

        String msg = "Deleted " + totalDeletedCats + " cat(s) and " + totalDeletedRelated + " related record(s).";
        JOptionPane.showMessageDialog(this, msg, "Deleted", JOptionPane.INFORMATION_MESSAGE);
        loadCats();
    }//GEN-LAST:event_DeleteCatsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteCats;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listCats;
    // End of variables declaration//GEN-END:variables
}
