package main;

import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class editAdoptersMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(editAdoptersMenu.class.getName());
    private Integer selectedAdopterId = null;

    public editAdoptersMenu() {
        initComponents();
        // load adopters into the list
        loadAdopters();

        // Wire selection listener
        listAdopters.addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting()) {
                Object sel = listAdopters.getSelectedValue();
                AdopterItem ct = (sel instanceof AdopterItem) ? (AdopterItem) sel : null;
                onAdopterSelected(ct);
            }
        });

        // Initially no selection: disable detail controls
        setDetailsEnabled(false);
    }

    private void setDetailsEnabled(boolean enabled) {
        changeDetailsPanel.setEnabled(enabled);
        nameField.setEnabled(enabled);
        contactField.setEnabled(enabled);
        SaveBtn.setEnabled(enabled);
        DeleteBtn.setEnabled(enabled);
    }

    private void loadAdopters() {
        SwingUtilities.invokeLater(() -> {
            DefaultListModel<AdopterItem> model = new DefaultListModel<>();
            String sql = "SELECT adopter_id, name, contact_info FROM adopter ORDER BY name";
            try (Connection conn = main.stuff.dbconn.getConnection(); PreparedStatement ps = conn.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    model.addElement(new AdopterItem(rs.getInt("adopter_id"),
                            rs.getString("name"),
                            rs.getString("contact_info")));
                }
            } catch (SQLException ex) {
                logger.log(java.util.logging.Level.WARNING, "Failed to load adopters", ex);
                model.clear();
                model.addElement(new AdopterItem(0, "<Error loading adopters>", ""));
            }

            // set model on EDT
            SwingUtilities.invokeLater(() -> {
                @SuppressWarnings("unchecked")
                javax.swing.JList<AdopterItem> lst = (javax.swing.JList<AdopterItem>) (Object) listAdopters;
                lst.setModel(model);
                // clear selection
                lst.clearSelection();
            });
        });
    }

    private void onAdopterSelected(AdopterItem ct) {
        if (ct == null) {
            selectedAdopterId = null;
            nameLabel.setText("");
            contactLabel.setText("");
            nameField.setText("");
            contactField.setText("");
            setDetailsEnabled(false);
            return;
        }

        selectedAdopterId = ct.id;
        nameLabel.setText(ct.name);
        contactLabel.setText(ct.contact == null ? "" : ct.contact);

        // fill change panel fields with current values
        nameField.setText(ct.name);
        contactField.setText(ct.contact == null ? "" : ct.contact);

        setDetailsEnabled(true);
    }

    private void selectAdopterInListById(int adopterId) {
        if (adopterId <= 0) {
            return;
        }
        @SuppressWarnings("unchecked")
        javax.swing.JList<AdopterItem> lst = (javax.swing.JList<AdopterItem>) (Object) listAdopters;
        javax.swing.ListModel<AdopterItem> model = lst.getModel();
        for (int i = 0; i < model.getSize(); i++) {
            AdopterItem ci = model.getElementAt(i);
            if (ci != null && ci.id == adopterId) {
                final int idx = i;
                SwingUtilities.invokeLater(() -> {
                    lst.setSelectedIndex(idx);
                    lst.ensureIndexIsVisible(idx);
                });
                return;
            }
        }
    }

    private static final class AdopterItem {

        final int id;
        final String name;
        final String contact;

        AdopterItem(int id, String name, String contact) {
            this.id = id;
            this.name = name == null ? "" : name;
            this.contact = contact == null ? "" : contact;
        }

        @Override
        public String toString() {
            return name;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAdopters = new javax.swing.JList<>();
        nameLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        changeDetailsPanel = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
        DeleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Caretakers Menu");
        setMinimumSize(new java.awt.Dimension(422, 350));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        listAdopters.setBorder(javax.swing.BorderFactory.createTitledBorder("List of Caretakers"));
        listAdopters.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listAdopters);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 20, 135, 124));

        nameLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 20, 220, -1));

        contactLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact"));
        getContentPane().add(contactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 65, 220, -1));

        changeDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Change Caretaker Details"));
        changeDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameField.setText("jTextField1");
        nameField.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));
        changeDetailsPanel.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 360, -1));

        contactField.setText("jTextField2");
        contactField.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact"));
        changeDetailsPanel.add(contactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 360, -1));

        getContentPane().add(changeDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 390, 130));

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        if (selectedAdopterId == null || selectedAdopterId == 0) {
            JOptionPane.showMessageDialog(this, "Please select an adopter to save changes.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String newName = nameField.getText() == null ? "" : nameField.getText().trim();
        String newContact = contactField.getText() == null ? "" : contactField.getText().trim();

        if (newName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Adopter name is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String updateSql = "UPDATE adopter SET name = ?, contact_info = ? WHERE adopter_id = ?";

        try (Connection conn = main.stuff.dbconn.getConnection()) {
            try {
                conn.setAutoCommit(false);

                try (PreparedStatement ps = conn.prepareStatement(updateSql)) {
                    ps.setString(1, newName);
                    ps.setString(2, newContact.isEmpty() ? null : newContact);
                    ps.setInt(3, selectedAdopterId);
                    ps.executeUpdate();
                }

                conn.commit();
            } catch (SQLException ex) {
                try {
                    conn.rollback();
                } catch (Throwable ignored) {
                }
                throw ex;
            } finally {
                try {
                    conn.setAutoCommit(true);
                } catch (Throwable ignored) {
                }
            }
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Failed to save adopter changes", ex);
            JOptionPane.showMessageDialog(this, "Failed to save changes: " + ex.getMessage(), "DB error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, "Adopter updated.", "Success", JOptionPane.INFORMATION_MESSAGE);
        // reload list and re-select
        loadAdopters();
        SwingUtilities.invokeLater(() -> selectAdopterInListById(selectedAdopterId));
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        if (selectedAdopterId == null || selectedAdopterId == 0) {
            JOptionPane.showMessageDialog(this, "Please select an adopter to delete.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Delete adopter? This cannot be undone.",
                "Confirm delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String deleteSql = "DELETE FROM adopter WHERE adopter_id = ?";

        try (Connection conn = main.stuff.dbconn.getConnection()) {
            try {
                conn.setAutoCommit(false);
                try (PreparedStatement ps = conn.prepareStatement(deleteSql)) {
                    ps.setInt(1, selectedAdopterId);
                    int affected = ps.executeUpdate();
                    if (affected == 0) {
                        throw new SQLException("No adopter removed (it may have already been deleted).");
                    }
                }
                conn.commit();
            } catch (SQLException ex) {
                try {
                    conn.rollback();
                } catch (Throwable ignored) {
                }
                throw ex;
            } finally {
                try {
                    conn.setAutoCommit(true);
                } catch (Throwable ignored) {
                }
            }
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Failed to delete adopter", ex);
            JOptionPane.showMessageDialog(this, "Failed to delete adopter: " + ex.getMessage(), "DB error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, "Adopter deleted.", "Success", JOptionPane.INFORMATION_MESSAGE);
        // refresh list and clear selection
        loadAdopters();
        SwingUtilities.invokeLater(() -> onAdopterSelected(null));
    }//GEN-LAST:event_DeleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JPanel changeDetailsPanel;
    private javax.swing.JTextField contactField;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listAdopters;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
