package main;

import main.stuff.dbconn;

import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.regex.Pattern;

public class signupMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(signupMenu.class.getName());
    private static final java.util.regex.Pattern EMAIL_PATTERN = java.util.regex.Pattern.compile("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$");
    private static final java.util.regex.Pattern PHONE_PATTERN = java.util.regex.Pattern.compile("^\\d{11}$");
    
    public signupMenu() {
        initComponents();
    }

    private void registerUser(String name, String username, String contact, String passwordPlain) {
        try (Connection conn = dbconn.getConnection()) {
            conn.setAutoCommit(false);
            // 1) check username uniqueness
            final String checkSql = "SELECT account_id FROM accounts WHERE username = ? LIMIT 1";
            try (PreparedStatement psCheck = conn.prepareStatement(checkSql)) {
                psCheck.setString(1, username);
                try (ResultSet rs = psCheck.executeQuery()) {
                    if (rs.next()) {
                        SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "Username is already taken.", "Registration failed", JOptionPane.ERROR_MESSAGE));
                        conn.rollback();
                        return;
                    }
                }
            }

            // 2) insert caretaker and get generated id
            int caretakerId = 0;
            final String insertCaretaker = "INSERT INTO caretaker (name, contact_info) VALUES (?, ?)";
            try (PreparedStatement psCaret = conn.prepareStatement(insertCaretaker, Statement.RETURN_GENERATED_KEYS)) {
                psCaret.setString(1, name);
                psCaret.setString(2, contact);
                int affected = psCaret.executeUpdate();
                if (affected == 0) {
                    throw new SQLException("Creating caretaker failed, no rows affected.");
                }
                try (ResultSet keys = psCaret.getGeneratedKeys()) {
                    if (keys.next()) {
                        caretakerId = keys.getInt(1);
                    } else {
                        // fallback: keep 0 (admin entry uses 0 in provided dump)
                        caretakerId = 0;
                    }
                }
            }

            // 3) insert account
            final String insertAccount = "INSERT INTO accounts (username, password, account_type, caretaker_id) VALUES (?, ?, ?, ?)";
            try (PreparedStatement psAcc = conn.prepareStatement(insertAccount, Statement.RETURN_GENERATED_KEYS)) {
                psAcc.setString(1, username);
                psAcc.setString(2, passwordPlain);
                psAcc.setString(3, "caretaker");
                psAcc.setInt(4, caretakerId);
                int affected = psAcc.executeUpdate();
                if (affected == 0) {
                    throw new SQLException("Creating account failed, no rows affected.");
                }
            }

            conn.commit();
            SwingUtilities.invokeLater(() -> {
                JOptionPane.showMessageDialog(this, "Registration successful. Your account will be verified by the administrators.", "Success", JOptionPane.INFORMATION_MESSAGE);
                // Optionally close the signup window after successful registration:
                this.dispose();
            });
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, "Database error during registration", ex);
            SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "An error occurred while creating your account. Please try again later.", "Registration error", JOptionPane.ERROR_MESSAGE));
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Unexpected error during registration", ex);
            SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "An unexpected error occurred. Please try again later.", "Registration error", JOptionPane.ERROR_MESSAGE));
        }
    }

    private static boolean isValidEmail(String email) {
        if (email == null) {
            return false;
        }
        return EMAIL_PATTERN.matcher(email).matches();
    }

    private static boolean isValidPhone(String phone) {
        if (phone == null) {
            return false;
        }
        // allow common separators but validate on digits count
        String digits = phone.replaceAll("\\D", "");
        return PHONE_PATTERN.matcher(digits).matches();
    }

    private static boolean isValidContact(String contact) {
        return isValidEmail(contact) || isValidPhone(contact);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        UsernameField = new javax.swing.JTextField();
        ContactField = new javax.swing.JTextField();
        PassField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        ConfirmPassField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        RegisterBtn = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign Up");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(788, 312));
        setMinimumSize(new java.awt.Dimension(788, 312));
        setPreferredSize(new java.awt.Dimension(788, 312));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Signup process will take a few days. Verification process will be done through email and or interviews on video call");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        NameField.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 300, -1));

        UsernameField.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        getContentPane().add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 320, -1));

        ContactField.setBorder(javax.swing.BorderFactory.createTitledBorder("Email or Contact Number"));
        getContentPane().add(ContactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 300, -1));

        PassField.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        getContentPane().add(PassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 320, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setText("Sign Up");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        ConfirmPassField.setBorder(javax.swing.BorderFactory.createTitledBorder("Confirm Password"));
        getContentPane().add(ConfirmPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 320, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setText("Information");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        RegisterBtn.setText("Sign up");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed

        final String name = NameField.getText().trim();
        final String username = UsernameField.getText().trim();
        final String contact = ContactField.getText().trim();
        final char[] pass = PassField.getPassword();
        final char[] confirm = ConfirmPassField.getPassword();

        if (name.isEmpty() || username.isEmpty() || contact.isEmpty() || pass.length == 0 || confirm.length == 0) {
            JOptionPane.showMessageDialog(this, "Please fill out all fields.", "Validation error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!java.util.Arrays.equals(pass, confirm)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.", "Validation error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!isValidContact(contact)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.", "Validation error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        RegisterBtn.setEnabled(false);

        new Thread(() -> {
            try {
                registerUser(name, username, contact, new String(pass));
            } finally {
                java.util.Arrays.fill(pass, '\0');
                java.util.Arrays.fill(confirm, '\0');
                SwingUtilities.invokeLater(() -> RegisterBtn.setEnabled(true));
            }
        }).start();
    }//GEN-LAST:event_RegisterBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPassField;
    private javax.swing.JTextField ContactField;
    private javax.swing.JTextField NameField;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
